version: '3.4'

volumes:
  postgres_data:

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pipeline:
    image: etl-pipeline
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['python', 'src/main.py']

  api:
    image: etl-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['uvicorn', 'src.api:app', '--host', '0.0.0.0', '--port', '80']
    ports:
      - '80:80'

  vite:
    image: etl-vite
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
